name: Build

on: push

jobs:
  build-win64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true

      - uses: msys2/setup-msys2@v2
        with:
          install: make mingw-w64-x86_64-gcc mingw-w64-x86_64-cmake mingw-w64-x86_64-winpthreads-git mingw-w64-x86_64-SDL2 mingw-w64-x86_64-glew

      - name: Build NanoboyAdvance
        run: |
          mkdir build
          cd build
          cmake -G "Unix Makefiles" -DCMAKE_CXX_FLAGS="-s" -DCMAKE_EXE_LINKER_FLAGS="-static -static-libgcc -static-libstdc++ -lstdc++" -DSDL2_STATIC=ON -DGLEW_USE_STATIC_LIBS=ON -DCMAKE_BUILD_TYPE=Release ..
          VERBOSE=1 make

      - name: Collect files
        run: |
          mkdir upload
          mv build/source/platform/sdl/NanoboyAdvance.exe upload
          mv build/source/platform/sdl/config.toml upload
          mv build/source/platform/sdl/keymap.toml upload
          mv build/source/platform/sdl/shader upload/shader

      - name: Upload files
        uses: actions/upload-artifact@master
        with:
          name: NanoboyAdvance-windows-gcc
          path: upload

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Setup submodules
        run: git submodule update --init

      - name: Setup SDL2
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install libsdl2-dev

      - name: Setup GLEW
        run: sudo apt-get install libglew-dev

      - name: Build NanoboyAdvance
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make

      - name: Collect files
        run: |
          mkdir upload
          mv build/source/platform/sdl/NanoboyAdvance upload
          mv build/source/platform/sdl/config.toml upload
          mv build/source/platform/sdl/keymap.toml upload
          mv build/source/platform/sdl/shader upload/shader

      - name: Upload files
        uses: actions/upload-artifact@master
        with:
          name: NanoboyAdvance-linux
          path: upload

  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@master

      - name: Setup submodules
        run: git submodule update --init

      - name: Setup SDL2
        run: brew install sdl2

      - name: Setup GLEW
        run: brew install glew

      - name: Build NanoboyAdvance
        run: |
          mkdir build
          cd build
          export CPPFLAGS="$CPPFLAGS -I/usr/local/opt/glew/include"
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make

      - name: Collect files
        run: |
          mkdir upload
          mv build/source/platform/sdl/NanoboyAdvance upload
          mv build/source/platform/sdl/config.toml upload
          mv build/source/platform/sdl/keymap.toml upload
          mv build/source/platform/sdl/shader upload/shader


      - name: Upload files
        uses: actions/upload-artifact@master
        with:
          name: NanoboyAdvance-macos
          path: upload
