name: Build

on: push

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@master

      - name: Setup submodules
        run: git submodule update --init
        shell: cmd

      - name: Setup vcpkg
        run: |
          Remove-Item "C:\vcpkg" -Recurse -Force
          $Uri = 'https://github.com/Microsoft/vcpkg.git'
          $InstallDir = 'C:\vcpkg'

          git clone -b 2020.04 --single-branch --depth=1 $Uri $InstallDir -q

          Invoke-Expression "$InstallDir\bootstrap-vcpkg.bat"
          vcpkg integrate install

      - name: Setup SDL2
        run: vcpkg install sdl2:x64-windows
        shell: cmd

      - name: Setup GLEW
        run: vcpkg install glew:x64-windows
        shell: cmd

      - name: Generate solution
        run: |
          mkdir build
          cd build
          set VCPKG_ROOT=C:/vcpkg
          cmake -DCMAKE_BUILD_TYPE=Release -T clangcl ..
        shell: cmd

      - name: Build NanoboyAdvance
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          msbuild /property:Configuration=Release build\NanoboyAdvance.sln
        shell: cmd

      - name: Collect files
        run: |
          mkdir upload
          move build\source\platform\sdl\Release\NanoboyAdvance.exe upload
          move build\source\platform\sdl\Release\glew32.dll upload
          move build\source\platform\sdl\Release\SDL2.dll upload
          move build\source\platform\sdl\shader upload\shader
          move source\platform\sdl\keymap.toml upload
          move config.toml upload
        shell: cmd

      - name: Upload files
        uses: actions/upload-artifact@master
        with:
          name: NanoboyAdvance-windows
          path: upload

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Setup submodules
        run: git submodule update --init

      - name: Setup SDL2
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install libsdl2-dev

      - name: Setup GLEW
        run: sudo apt-get install libglew-dev

      - name: Build NanoboyAdvance
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make

      - name: Collect files
        run: |
          mkdir upload
          mv build/source/platform/sdl/NanoboyAdvance upload
          mv build/source/platform/sdl/config.toml upload
          mv build/source/platform/sdl/keymap.toml upload
          mv build/source/platform/sdl/shader upload/shader

      - name: Upload files
        uses: actions/upload-artifact@master
        with:
          name: NanoboyAdvance-linux
          path: upload

  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@master

      - name: Setup submodules
        run: git submodule update --init

      - name: Setup SDL2
        run: brew install sdl2

      - name: Setup GLEW
        run: brew install glew

      - name: Build NanoboyAdvance
        run: |
          mkdir build
          cd build
          export CPPFLAGS="$CPPFLAGS -I/usr/local/opt/glew/include"
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make

      - name: Collect files
        run: |
          mkdir upload
          mv build/source/platform/sdl/NanoboyAdvance upload
          mv build/source/platform/sdl/config.toml upload
          mv build/source/platform/sdl/keymap.toml upload
          mv build/source/platform/sdl/shader upload/shader


      - name: Upload files
        uses: actions/upload-artifact@master
        with:
          name: NanoboyAdvance-macos
          path: upload
